/*
The MIT License

Copyright (c) 2012 Universidad Politecnica de Madrid

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.*/
var XMLHttpRequest = require("./../vendor/xmlhttprequest").XMLHttpRequest;
var JSTACK=JSTACK||{};JSTACK.VERSION="0.1";JSTACK.AUTHORS="GING";JSTACK.Comm=function(e,c){var h;h=function(e,h,a,b,d,f,i){var m,k,f=f||function(){},d=d||function(){};m=new XMLHttpRequest;m.open(e,h,!0);m.setRequestHeader("Accept","application/json");b!==c&&m.setRequestHeader("X-Auth-Token",b);e=!1;if(i)for(var l in i)"Content-Type"===l&&(e=!0),m.setRequestHeader(l,i[l]),console.log("Header set: ",l," - ",i[l]);a&&!e&&m.setRequestHeader("Content-Type","application/json");m.onerror=function(a){f({message:"Error",body:a})};m.onreadystatechange=function(){if(!n&&
4===m.readyState)switch(n=!0,m.status){case 100:case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 207:k=c;m.responseText!==c&&""!==m.responseText&&(k=JSON.parse(m.responseText));d(k,m.getAllResponseHeaders(),m.getResponseHeader("x-subject-token"));break;default:f({message:m.status+" Error",body:m.responseText})}};var n=!1;if(a!==c){a=JSON.stringify(a);try{m.send(a)}catch(o){}}else try{m.send()}catch(q){}};return{get:function(e,g,a,b){h("get",e,c,g,a,b)},head:function(e,g,a,b){h("head",
e,c,g,a,b)},post:function(c,e,a,b,d){h("POST",c,e,a,b,d)},put:function(c,e,a,b,d,f){h("PUT",c,e,a,b,d,f)},patch:function(c,e,a,b,d,f){f["Content-Type"]="application/openstack-images-v2.1-json-patch";h("PATCH",c,e,a,b,d,f)},del:function(e,g,a,b){h("DELETE",e,c,g,a,b)},getEndpoint:function(c,e,a){var b;if(3===JSTACK.Keystone.params.version){var a=a.split("URL")[0],d;for(d in c.endpoints)if(c.endpoints[d].region===e&&c.endpoints[d]["interface"]===a){b=c.endpoints[d].url;break}}else for(d in c.endpoints)if(c.endpoints[d].region===
e){b=c.endpoints[d][a];break}return b}}}(JSTACK);JSTACK.Utils=function(){var e,c,h,j,g,a,b,d,f;e="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");c=[];for(g=0;g<e.length;g+=1)c[e[g]]=g;a=function(a){h=a;j=0};b=function(){var a;if(!h||j>=h.length)return-1;a=h.charCodeAt(j)&255;j+=1;return a};d=function(){if(!h)return-1;for(;;){if(j>=h.length)return-1;var a=h.charAt(j);j+=1;if(c[a])return c[a];if("A"===a)return 0}};f=function(a){a=a.toString(16);1===a.length&&
(a="0"+a);return unescape("%"+a)};return{encode:function(d){var c,f,h;a(d);d="";c=Array(3);f=0;for(h=!1;!h&&-1!==(c[0]=b());)if(c[1]=b(),c[2]=b(),d+=e[c[0]>>2],-1!==c[1]?(d+=e[c[0]<<4&48|c[1]>>4],-1!==c[2]?(d+=e[c[1]<<2&60|c[2]>>6],d+=e[c[2]&63]):(d+=e[c[1]<<2&60],d+="=",h=!0)):(d+=e[c[0]<<4&48],d+="=",d+="=",h=!0),f+=4,76<=f)d+="\n",f=0;return d},decode:function(b){var c,e;a(b);b="";c=Array(4);for(e=!1;!e&&-1!==(c[0]=d())&&-1!==(c[1]=d());)c[2]=d(),c[3]=d(),b+=f(c[0]<<2&255|c[1]>>4),-1!==c[2]?(b+=
f(c[1]<<4&255|c[2]>>2),-1!==c[3]?b+=f(c[2]<<6&255|c[3]):e=!0):e=!0;return b}}}(JSTACK);JSTACK.Keystone=function(e,c){var h,j,g;j={DISCONNECTED:0,AUTHENTICATING:1,AUTHENTICATED:2,AUTHENTICATION_ERROR:3};h={url:c,currentstate:c,access:c,token:c};g=function(a){var b,d;if(h.currentstate!==j.AUTHENTICATED)return c;for(b in h.access.serviceCatalog)if(h.access.serviceCatalog[b]!==c&&(d=h.access.serviceCatalog[b],a===d.type))return d;return c};return{STATES:j,params:h,init:function(a,b){console.log("Admin URL"+b);h.url=a;h.adminUrl=b;h.access=c;h.token=c;h.access_token=c;h.currentstate=j.DISCONNECTED;
h.version=-1===a.indexOf("v3")?2:3},authenticate:function(a,b,d,f,i,m){var g={},l;3===h.version?(g=d!==c?{auth:{identity:{methods:["oauth2"],oauth2:{access_token_id:d}}}}:{auth:{passwordCredentials:{username:a,password:b}}},f!==c&&(g.auth.scope={project:{id:f}})):(g=d!==c?{auth:{token:{id:d}}}:{auth:{passwordCredentials:{username:a,password:b}}},f!==c&&(g.auth.tenantId=f));h.currentstate=j.AUTHENTICATING;l=function(a){h.currentstate=e.Keystone.STATES.AUTHENTICATED;h.access=a.access;h.token=h.access.token.id;
i!==c&&i(a)};a=function(a){h.currentstate=j.AUTHENTICATION_ERROR;m(a)};3===h.version?e.Comm.post(h.url+"auth/tokens",g,c,function(a,b,d){l({access:{token:{id:d,expires:a.token.expires_at,tenant:{id:a.token.project.id,name:a.token.project.name}},serviceCatalog:a.token.catalog,user:a.token.user}})},a):e.Comm.post(h.url+"tokens",g,c,l,a)},gettenants:function(a,b,d){var f,i;f=function(b){a!==c&&a(b)};i=function(a){d!==c&&d(a)};var g=h.url;b&&(g=h.adminUrl);3===h.version?e.Comm.get(g+"authorized_organizations/"+
h.access_token,c,function(a){f({tenants:a.organizations})},i):e.Comm.get(g+"tenants",h.token,f,i)},getendpoint:function(a,b){var d=g(b)||{},c,i;for(i in d.endpoints)if(d.endpoints[i].region===a){c=d.endpoints[i];break}return c},getservice:g,getservicelist:function(){return h.currentstate!==j.AUTHENTICATED?c:h.access.serviceCatalog},createuser:function(a,b,d,c,i,g,j){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.post(h.adminUrl+"users",{user:{name:a,password:b,tenantId:d,email:c,enabled:i}},
h.token,g,j)},edituser:function(a,b,d,f,i,g,j,l){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&(b={user:{name:b,tenantId:f,email:i,enabled:g}},d!==c&&(b.user.password=d),e.Comm.put(h.adminUrl+"users/"+a,b,h.token,j,l))},getusers:function(a,b){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.get(h.adminUrl+"users",h.token,a,b)},getusersfortenant:function(a,b,d){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.get(h.adminUrl+"tenants/"+a+"/users",h.token,b,d)},getuser:function(a,
b,d){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.get(h.adminUrl+"users/"+a,h.token,b,d)},deleteuser:function(a,b,d){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.del(h.adminUrl+"users/"+a,h.token,b,d)},getuserroles:function(a,b,d,f){if(h.currentstate===e.Keystone.STATES.AUTHENTICATED){var i="",i=b!==c?h.adminUrl+"tenants/"+b+"/users/"+a+"/roles":h.adminUrl+"users/"+a+"/roles";e.Comm.get(i,h.token,d,f)}},getroles:function(a,b){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&
e.Comm.get(h.adminUrl+"OS-KSADM/roles",h.token,a,b)},adduserrole:function(a,b,d,f,i){if(h.currentstate===e.Keystone.STATES.AUTHENTICATED){var g="",g=d!==c?h.adminUrl+"tenants/"+d+"/users/"+a+"/roles/OS-KSADM/"+b:h.adminUrl+"users/"+a+"/roles/OS-KSADM/"+b;e.Comm.put(g,{},h.token,f,i)}},removeuserrole:function(a,b,d,f,i){if(h.currentstate===e.Keystone.STATES.AUTHENTICATED){var g="",g=d!==c?h.adminUrl+"tenants/"+d+"/users/"+a+"/roles/OS-KSADM/"+b:h.adminUrl+"users/"+a+"/roles/OS-KSADM/"+b;e.Comm.del(g,
h.token,f,i)}},createtenant:function(a,b,d,c,i){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.post(h.adminUrl+"tenants",{tenant:{name:a,description:b,enabled:d}},h.token,c,i)},edittenant:function(a,b,d,c,i,g){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.put(h.adminUrl+"tenants/"+a,{tenant:{id:a,name:b,description:d,enabled:c}},h.token,i,g)},deletetenant:function(a,b,d){h.currentstate===e.Keystone.STATES.AUTHENTICATED&&e.Comm.del(h.adminUrl+"tenants/"+a,h.token,b,d)}}}(JSTACK);JSTACK.Nova=function(e,c){var h,j,g;h={url:c,state:c,endpointType:"publicURL",service:"compute"};j=function(a){if(e.Keystone!==c&&e.Keystone.params.currentstate===e.Keystone.STATES.AUTHENTICATED){var b=e.Keystone.getservice(h.service);if(b)return h.url=JSTACK.Comm.getEndpoint(b,a,h.endpointType),!0}return!1};g=function(a,b,d,f,i){j(i)&&(a=h.url+"/servers/"+a+"/action",e.Comm.post(a,b,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))};return{configure:function(a){if("adminURL"===
a||"internalURL"===a||"publicURL"===a)h.endpointType=a},params:h,getserverlist:function(a,b,d,f,i){j(i)&&(i=h.url+"/servers",a!==c&&a&&(i+="/detail"),b&&(i+="?all_tenants="+b),e.Comm.get(i,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},getserverdetail:function(a,b,d,f){j(f)&&(a=h.url+"/servers/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getserverips:function(a,b,d,f,i){j(i)&&(a=h.url+"/servers/"+a+"/ips",b!==c&&(a+="/"+
b),e.Comm.get(a,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},updateserver:function(a,b,d,f,i){j(i)&&(a=h.url+"/servers/"+a,b!==c&&e.Comm.put(a,{server:{name:b}},e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},createserver:function(a,b,d,f,i,g,k,l,n,o,q,p,r,t,v){var u=[],s;if(j(v)){a={server:{name:a,imageRef:b,flavorRef:d}};p&&(a.server.metadata=p);p=q!==c?"/os-volumes_boot":"/servers";f!==c&&(a.server.key_name=f);i!==c&&(a.server.user_data=
e.Utils.encode(i));q!==c&&(a.server.block_device_mapping=q);if(g!==c){for(s in g)g[s]!==c&&(f={name:g[s]},u.push(f));a.server.security_groups=u}k===c&&(k=1);a.server.min_count=k;l===c&&(l=1);a.server.max_count=l;n!==c&&(a.server.availability_zone=e.Utils.encode(n));o!==c&&(a.server.networks=o);e.Comm.post(h.url+p,a,e.Keystone.params.token,function(a){r!==c&&r(a)},function(a){t!==c&&t(a)})}},deleteserver:function(a,b,d,f){j(f)&&(a=h.url+"/servers/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==
c&&b(a)},function(a){d!==c&&d(a)}))},changepasswordserver:function(a,b,d,f,i){b!==c&&g(a,{changePassword:{adminPass:b}},d,f,i)},rebootserverhard:function(a,b,d,c){g(a,{reboot:{type:"HARD"}},b,d,c)},rebootserversoft:function(a,b,d,c){g(a,{reboot:{type:"SOFT"}},b,d,c)},resizeserver:function(a,b,d,c,i){g(a,{resize:{flavorRef:b}},d,c,i)},confirmresizedserver:function(a,b,d,c){g(a,{confirmResize:null},b,d,c)},revertresizedserver:function(a,b,c,f){g(a,{revertResize:null},b,c,f)},startserver:function(a,
b,c,f){g(a,{"os-start":null},b,c,f)},stopserver:function(a,b,c,f){g(a,{"os-stop":null},b,c,f)},pauseserver:function(a,b,c,f){g(a,{pause:null},b,c,f)},unpauseserver:function(a,b,c,f){g(a,{unpause:null},b,c,f)},suspendserver:function(a,b,c,f){g(a,{suspend:null},b,c,f)},resumeserver:function(a,b,c,f){g(a,{resume:null},b,c,f)},createimage:function(a,b,d,f,i,e){b={createImage:{name:b}};b.createImage.metadata={};d!==c&&(b.createImage.metadata=d);g(a,b,f,i,e)},getflavorlist:function(a,b,d,f){j(f)&&(f=h.url+
"/flavors",a!==c&&a&&(f+="/detail"),e.Comm.get(f,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getflavordetail:function(a,b,d,f){j(f)&&(a=h.url+"/flavors/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},createflavor:function(a,b,d,f,i,g,k,l,n,o,q){j(q)&&(q=h.url+"/flavors",a={flavor:{name:a,ram:b,vcpus:d,disk:f,id:i+"",swap:0,"OS-FLV-EXT-DATA:ephemeral":0,rxtx_factor:0}},g!==c&&(a.flavor["OS-FLV-EXT-DATA:ephemeral"]=g),k!==
c&&(a.flavor.swap=k),l!==c&&(a.flavor.rxtx_factor=l),e.Comm.post(q,a,e.Keystone.params.token,function(a){n!==c&&n(a)},function(a){o!==c&&o(a)}))},deleteflavor:function(a,b,d,f){j(f)&&(a=h.url+"/flavors/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getimagelist:function(a,b,d,f){j(f)&&(f=h.url+"/images",a!==c&&a&&(f+="/detail"),e.Comm.get(f+"?limit=100",e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getimagedetail:function(a,
b,d,f){j(f)&&(a=h.url+"/images/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},deleteimage:function(a,b,d,f){j(f)&&(a=h.url+"/images/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getkeypairlist:function(a,b,d){j(d)&&(d=h.url+"/os-keypairs",e.Comm.get(d,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},createkeypair:function(a,b,d,f,i){j(i)&&(i=h.url+"/os-keypairs",a={keypair:{name:a}},
b!==c&&(a.keypair.public_key=b),e.Comm.post(i,a,e.Keystone.params.token,function(a){d!==c&&d(a.keypair)},function(a){f!==c&&f(a)}))},deletekeypair:function(a,b,d,f){j(f)&&(a=h.url+"/os-keypairs/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getkeypairdetail:function(a,b,d,f){j(f)&&(a=h.url+"/os-keypairs/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getvncconsole:function(a,b,d,f,e){if(j(e)){if(b===c||!b)b=
"novnc";g(a,{"os-getVNCConsole":{type:b}},d,f,e)}},getconsoleoutput:function(a,b,d,f,e){if(j(e)){if(b===c||!b)b=35;g(a,{"os-getConsoleOutput":{length:b}},d,f,e)}},getattachedvolumes:function(a,b,d,f){j(f)&&(a=h.url+"/servers/"+a+"/os-volume_attachments",e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},attachvolume:function(a,b,d,f,i,g){j(g)&&(a=h.url+"/servers/"+a+"/os-volume_attachments",b===c||d===c||e.Comm.post(a,{volumeAttachment:{volumeId:b,device:d}},
e.Keystone.params.token,function(a){f!==c&&f(a)},function(a){i!==c&&i(a)}))},detachvolume:function(a,b,d,f,i){j(i)&&(a=h.url+"/servers/"+a+"/os-volume_attachments/"+b,b!==c&&e.Comm.del(a,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},getattachedvolume:function(a,b,d,f,i){j(i)&&(a=h.url+"/servers/"+a+"/os-volume_attachments/"+b,b!==c&&e.Comm.get(a,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},getquotalist:function(a,b,d,f){j(f)&&(a=h.url+
"/os-quota-sets/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},updatequota:function(a,b,d,f,i,g,k,l,n,o,q,p,r,t,v,u,s){if(j(s)&&(s=h.url+"/os-quota-sets/"+a,!(b==c&&d==c&&f==c&&i==c&&g==c&&k==c&&l==c&&n==c&&o==c&&q==c&&p==c&&r==c&&t==c))){var a={quota_set:{instances:b,cores:d,ram:f,volumes:i,gigabytes:g,floating_ips:k,metadata_items:l,injected_files:n,injected_file_content_bytes:o,injected_file_path_bytes:q,security_groups:p,security_group_rules:r,key_pairs:t,
id:a}},w;for(w in a.quota_set)a.quota_set[w]==c&&delete a.quota_set[w];e.Comm.put(s,a,e.Keystone.params.token,function(a){v!==c&&v(a)},function(a){u!==c&&u(a)})}},getdefaultquotalist:function(a,b,d,f){j(f)&&(a=h.url+"/os-quota-sets/"+a+"/defaults",e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getsecuritygrouplist:function(a,b,d){j(d)&&(d=h.url+"/os-security-groups",e.Comm.get(d,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},
createsecuritygroup:function(a,b,d,f,i){j(i)&&(i=h.url+"/os-security-groups",a={security_group:{name:a,description:b}},e.Comm.post(i,a,e.Keystone.params.token,function(a){console.log(d);d!==c&&d(a)},function(a){f!==c&&f(a)}))},getsecuritygroupdetail:function(a,b,d,f){j(f)&&(a=h.url+"/os-security-groups/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},deletesecuritygroup:function(a,b,d,f){j(f)&&(a=h.url+"/os-security-groups/"+a,e.Comm.del(a,e.Keystone.params.token,
function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},createsecuritygrouprule:function(a,b,d,f,i,g,k,l,n){j(n)&&(n=h.url+"/os-security-group-rules",a={security_group_rule:{ip_protocol:a,from_port:b,to_port:d,cidr:f,group_id:i,parent_group_id:g}},e.Comm.post(n,a,e.Keystone.params.token,function(a){k!==c&&k(a)},function(a){l!==c&&l(a)}))},deletesecuritygrouprule:function(a,b,d,f){j(f)&&(a=h.url+"/os-security-group-rules/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==
c&&d(a)}))},getsecuritygroupforserver:function(a,b,d,f){j(f)&&(a=h.url+"/servers/"+a+"/os-security-groups",e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getfloatingIPpools:function(a,b,d){j(d)&&(d=h.url+"/os-floating-ip-pools",e.Comm.get(d,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b(a);throw Error(a);}))},getfloatingIPs:function(a,b,d){j(d)&&(d=h.url+"/os-floating-ips",e.Comm.get(d,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b(a);
throw Error(a);}))},getfloatingIPdetail:function(a,b,d,f){j(f)&&(a=h.url+"/os-floating-ips/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d(a);throw Error(a);}))},allocatefloatingIP:function(a,b,d,f){var g;j(f)&&(f=h.url+"/os-floating-ips",a!==c&&(g={pool:a}),e.Comm.post(f,g,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d(a);throw Error(a);}))},associatefloatingIP:function(a,b,d,f,g,m){j(m)&&(a=h.url+"/servers/"+a+"/action",b={addFloatingIp:{address:b}},
d!==c&&(b.addFloatingIp.fixed_address=d),e.Comm.post(a,b,e.Keystone.params.token,function(a){f!==c&&f(a)},function(a){g(a);throw Error(a);}))},disassociatefloatingIP:function(a,b,d,f,g){j(g)&&(a=h.url+"/servers/"+a+"/action",e.Comm.post(a,{removeFloatingIp:{address:b}},e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f(a);throw Error(a);}))},releasefloatingIP:function(a,b,d,f){j(f)&&(a=h.url+"/os-floating-ips/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d(a);
throw Error(a);}))}}}(JSTACK);JSTACK.Cinder=function(e,c){var h,j,g;h=c;j="publicURL";g=function(a){if(e.Keystone!==c&&e.Keystone.params.currentstate===e.Keystone.STATES.AUTHENTICATED){var b=e.Keystone.getservice("volume");if(b)return h=JSTACK.Comm.getEndpoint(b,a,j),!0}return!1};return{configure:function(a){if("adminURL"===a||"internalURL"===a||"publicURL"===a)j=a},getvolumelist:function(a,b,d,f){g(f)&&(f=h+"/volumes",a!==c&&a&&(f+="/detail"),e.Comm.get(f,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},
createvolume:function(a,b,d,f,i,j){g(j)&&(a={volume:{size:a}},b!==c&&(a.volume.display_name=b),d!==c&&(a.volume.display_description=d),e.Comm.post(h+"/volumes",a,e.Keystone.params.token,function(a){f!==c&&f(a)},function(a){i!==c&&i(a)}))},deletevolume:function(a,b,d,f){g(f)&&(a=h+"/volumes/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getvolume:function(a,b,d,f){g(f)&&(a=h+"/volumes/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==
c&&d(a)}))},getsnapshotlist:function(a,b,d,f){g(f)&&(f=h+"/snapshots",a!==c&&a&&(f+="/detail"),e.Comm.get(f,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},createsnapshot:function(a,b,d,f,i,j){g(j)&&(a={snapshot:{volume_id:a,force:!0}},b!==c&&(a.snapshot.display_name=b),d!==c&&(a.snapshot.display_description=d),e.Comm.post(h+"/snapshots",a,e.Keystone.params.token,function(a){f!==c&&f(a)},function(a){i!==c&&i(a)}))},deletesnapshot:function(a,b,d,f){g(f)&&(a=h+"/snapshots/"+
a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getsnapshot:function(a,b,d,f){g(f)&&(a=h+"/snapshots/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))}}}(JSTACK);JSTACK.Glance=function(e,c){var h,j,g,a;h=c;j="publicURL";g=function(a){if(e.Keystone!==c&&e.Keystone.params.currentstate===e.Keystone.STATES.AUTHENTICATED){var d=e.Keystone.getservice("image");h=JSTACK.Comm.getEndpoint(d,a,j);return!0}return!1};a=function(a){if(!g(a))return 0;var c=e.Keystone.getservice("image");h=JSTACK.Comm.getEndpoint(c,a,j);return h.match(/v1/)?1:h.match(/v2/)?2:0};return{configure:function(a){if("adminURL"===a||"internalURL"===a||"publicURL"===a)j=a},getimagelist:function(a,
d,f,i){g(i)&&(i=h+"/images",a!==c&&a&&i.match(/v1/)&&(i+="/detail"),e.Comm.get(i+"?limit=100",e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},getimagedetail:function(b,d,f,i){var j,k;if(g(i))switch(b=h+"/images/"+b,j=function(b,f){if(d!==c)switch(a(i)){case 1:var e={};f.split("\r\n").forEach(function(a){if(-1!==a.indexOf("x-image-meta")){var c=a.match(/^([\w\d\-\_]*)\: (.*)$/),a=c[2],c=c[1].split("-");e[c[c.length-1]]=a}});d(e,f);break;case 2:d(b)}},k=function(a){f!==
c&&f(a)},a(i)){case 1:e.Comm.head(b,e.Keystone.params.token,j,k);break;case 2:e.Comm.get(b,e.Keystone.params.token,j,k)}},updateimage:function(b,d,f,i,j,k,l){var n,o,q={};if(g(l))switch(b=h+"/images/"+b,n=function(a){j!==c&&j(a)},o=function(a){k!==c&&k(a)},a(l)){case 1:d&&(q["x-image-meta-name"]=d);q["x-image-meta-is_public"]="public"===f?"true":"false";var i=i||{},p;for(p in i)q["x-image-meta-property-"+p]=i[p];e.Comm.put(b,c,e.Keystone.params.token,n,o,q);break;case 2:i=[],d&&i.push({op:"replace",
path:"/name",value:d}),f&&i.push({op:"replace",path:"/visibility",value:f}),e.Comm.patch(b,i,e.Keystone.params.token,n,o,q)}},getVersion:a}}(JSTACK);JSTACK.Neutron=function(e,c){var h,j;h={url:c,state:c,endpointType:"publicURL"};j=function(g){if(e.Keystone!==c&&e.Keystone.params.currentstate===e.Keystone.STATES.AUTHENTICATED){var a=e.Keystone.getservice("network");if(a)return h.url=JSTACK.Comm.getEndpoint(a,g,h.endpointType),!0}return!1};return{params:h,configure:function(c){if("adminURL"===c||"internalURL"===c||"publicURL"===c)h.endpointType=c},getnetworkslist:function(g,a,b){j(b)&&(b=h.url+"v2.0/networks",e.Comm.get(b,e.Keystone.params.token,
function(a){g!==c&&g(a.networks)},function(b){a!==c&&a(b)}))},getnetworkdetail:function(g,a,b,d){j(d)&&(g=h.url+"v2.0/networks/"+g,e.Comm.get(g,e.Keystone.params.token,function(b){a!==c&&a(b.network)},function(a){b!==c&&b(a)}))},createnetwork:function(g,a,b,d,f,i,m){var k;j(m)&&(m=h.url+"v2.0/networks",k={network:{}},g!==c&&(k.network.name=g),a!==c&&(k.network.admin_state_up=a),b!==c&&(k.network.shared=b),d!==c&&(k.network.tenant_id=d),e.Comm.post(m,k,e.Keystone.params.token,function(a){f!==c&&f(a)},
function(a){i!==c&&i(a)}))},updatenetwork:function(g,a,b,d,f,i){j(i)&&(g=h.url+"v2.0/networks/"+g,i={network:{}},a!==c&&(i.network.name=a),b!==c&&(i.network.admin_state_up=b),e.Comm.put(g,i,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},deletenetwork:function(g,a,b,d){j(d)&&(g=h.url+"v2.0/networks/"+g,e.Comm.del(g,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},getsubnetslist:function(g,a,b){j(b)&&(b=h.url+"v2.0/subnets",e.Comm.get(b,e.Keystone.params.token,
function(a){g!==c&&g(a)},function(b){a!==c&&a(b)}))},getsubnetdetail:function(g,a,b,d){j(d)&&(g=h.url+"v2.0/subnets/"+g,e.Comm.get(g,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},createsubnet:function(g,a,b,d,f,i,m,k,l,n,o,q,p){j(p)&&(p=h.url+"v2.0/subnets",g={subnet:{network_id:g,cidr:a,ip_version:m}},b!==c&&(g.subnet.name=b),f!==c&&(g.subnet.tenant_id=f),d!==c&&(g.subnet.allocation_pools=d),i!==c&&(g.subnet.gateway_ip=i),k!==c&&(g.subnet.enable_dhcp=k),l!==c&&(g.subnet.dns_nameservers=
l),n!==c&&(g.subnet.host_routes=n),e.Comm.post(p,g,e.Keystone.params.token,function(a){o!==c&&o(a)},function(a){q!==c&&q(a)}))},updatesubnet:function(g,a,b,d,f,i,m,k,l){var n,o=[],q=[];if(j(l)){g=h.url+"v2.0/subnets/"+g;l={subnet:{}};a!==c&&(l.subnet.name=a);b!==c&&(l.subnet.gateway_ip=b);d!==c&&(l.subnet.enable_dhcp=d);if(f!==c){for(n in f)f[n]!==c&&(a=f[n],o.push(a));l.subnet.dns_nameservers=o}if(i!==c){for(n in i)i[n]!==c&&(f=i[n],q.push(f));l.subnet.host_routes=q}e.Comm.put(g,l,e.Keystone.params.token,
function(a){m!==c&&m(a)},function(a){k!==c&&k(a)})}},deletesubnet:function(g,a,b,d){j(d)&&(g=h.url+"v2.0/subnets/"+g,e.Comm.del(g,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},getportslist:function(g,a,b){j(b)&&(b=h.url+"v2.0/ports",e.Comm.get(b,e.Keystone.params.token,function(a){g!==c&&g(a)},function(b){a!==c&&a(b)}))},getportdetail:function(g,a,b,d){j(d)&&(g=h.url+"v2.0/ports/"+g,e.Comm.get(g,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},
createport:function(g,a,b,d,f,i,m,k,l,n,o){var q=[],p,r=[];if(j(o)){o=h.url+"v2.0/ports";g={port:{network_id:g}};i!==c&&(g.port.status=i);a!==c&&(g.port.name=a);f!==c&&(g.port.admin_state_up=f);m!==c&&(g.port.tenant_id=m);k!==c&&(g.port.mac_address=k);if(b!==c){for(p in b)b[p]!==c&&(a=b[p],r.push(a));g.port.fixed_ips=r}if(d!==c){for(p in d)d[p]!==c&&(b=d[p],q.push(b));g.port.security_groups=q}e.Comm.post(o,g,e.Keystone.params.token,function(a){l!==c&&l(a)},function(a){n!==c&&n(a)})}},updateport:function(g,
a,b,d,f,i,m,k,l,n,o){var q=[],p,r=[];if(j(o)){g=h.url+"v2.0/ports/"+g;o={port:{}};i!==c&&(o.port.status=i);a!==c&&(o.port.name=a);f!==c&&(o.port.admin_state_up=f);m!==c&&(o.port.tenant_id=m);k!==c&&(o.port.mac_address=k);if(b!==c){for(p in b)b[p]!==c&&(a=b[p],r.push(a));o.port.fixed_ips=r}if(d!==c){for(p in d)d[p]!==c&&(b=d[p],q.push(b));o.port.security_groups=q}e.Comm.put(g,o,e.Keystone.params.token,function(a){l!==c&&l(a)},function(a){n!==c&&n(a)})}},deleteport:function(g,a,b,d){j(d)&&(g=h.url+
"v2.0/ports/"+g,e.Comm.del(g,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},getrouterslist:function(g,a,b){j(b)&&(b=h.url+"v2.0/routers",e.Comm.get(b,e.Keystone.params.token,function(a){g!==c&&g(a)},function(b){a!==c&&a(b)}))},createrouter:function(g,a,b,d,f,i,m){var k;j(m)&&(m=h.url+"v2.0/routers",k={router:{external_gateway_info:{}}},b!==c&&(k.router.external_gateway_info.network_id=b),g!==c&&(k.router.name=g),a!==c&&(k.router.admin_state_up=a),d!==c&&(k.router.tenant_id=
d),e.Comm.post(m,k,e.Keystone.params.token,function(a){f!==c&&f(a)},function(a){i!==c&&i(a)}))},updaterouter:function(g,a,b,d,f,i,m){j(m)&&(g=h.url+"v2.0/routers/"+g,m={router:{external_gateway_info:{}}},a!==c&&(m.router.external_gateway_info.network_id=a),b!==c&&(m.router.name=b),d!==c&&(m.router.admin_state_up=d),e.Comm.put(g,m,e.Keystone.params.token,function(a){f!==c&&f(a)},function(a){i!==c&&i(a)}))},getrouterdetail:function(g,a,b,d){j(d)&&(g=h.url+"v2.0/routers/"+g,e.Comm.get(g,e.Keystone.params.token,
function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},deleterouter:function(g,a,b,d){j(d)&&(g=h.url+"v2.0/routers/"+g,e.Comm.del(g,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},addinterfacetorouter:function(g,a,b,d,f,i){j(i)&&(g=h.url+"v2.0/routers/"+g+"/add_router_interface",i={},a!==c&&(i.subnet_id=a),b!==c&&(i.port_id=b),e.Comm.put(g,i,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))},removeinterfacefromrouter:function(g,a,b,d,f,i){j(i)&&
(i={},g=h.url+"v2.0/routers/"+g+"/remove_router_interface",b!==c&&(i.subnet_id=b),a!==c&&(i.port_id=a),e.Comm.put(g,i,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))}}}(JSTACK);JSTACK.Swift=function(e,c){var h,j,g;h=c;j="publicURL";g=function(a){if(e.Keystone!==c&&e.Keystone.params.currentstate===e.Keystone.STATES.AUTHENTICATED){var b=e.Keystone.getservice("object-store");if(b)return h=JSTACK.Comm.getEndpoint(b,a,j),!0}return!1};return{configure:function(a){if("adminURL"===a||"internalURL"===a||"publicURL"===a)j=a},getcontainerlist:function(a,b,d){g(d)&&(d=h,e.Comm.get(d,e.Keystone.params.token,function(b){a!==c&&a(b)},function(a){b!==c&&b(a)}))},createcontainer:function(a,
b,d,f){g(f)&&(a=h+"/"+a,e.Comm.put(a,{metadata:{}},JSTACK.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},deletecontainer:function(a,b,d,f){g(f)&&(a=h+"/"+a,e.Comm.del(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},getobjectlist:function(a,b,d,f){g(f)&&(a=h+"/"+a,e.Comm.get(a,e.Keystone.params.token,function(a){b!==c&&b(a)},function(a){d!==c&&d(a)}))},copyobject:function(a,b,d,f,i,j,k){var l={};g(k)&&(d=h+"/"+d+"/"+f,l["X-Copy-From"]="/"+
a+"/"+b,l["Content-Length"]="0",console.log("Edited header content: "+l),e.Comm.put(d,c,e.Keystone.params.token,function(a){i!==c&&i(a)},function(a){j!==c&&j(a)},l))},uploadobject:function(a,b,d,f,i,j,k){g(k)&&(a=h+"/"+a+"/"+b,e.Comm.put(a,{mimeType:f,metadata:{},valuetransferencoding:"base64",value:d},e.Keystone.params.token,function(a){i!==c&&i(a)},function(a){j!==c&&j(a)}))},downloadobject:function(a,b,d,f,i){g(i)&&(a=h+"/"+a+"/"+b,e.Comm.get(a,e.Keystone.params.token,function(a){d!==c&&d(a)},
function(a){f!==c&&f(a)}))},deleteobject:function(a,b,d,f,i){g(i)&&(a=h+"/"+a+"/"+b,e.Comm.del(a,e.Keystone.params.token,function(a){d!==c&&d(a)},function(a){f!==c&&f(a)}))}}}(JSTACK);
module.exports = JSTACK;
